### PR TITLE
Adds a demo gif

### PR DESCRIPTION
**Pull request by s4cha**
Adds a demo gif to showcase the project.

### CODE REVIEW

**Comment by maxkonovalov** [comment]
Hey @s4cha, the example gif doesn't seem to loop. How about using this one instead?
I think it looks cleaner without the device border.
keyboardlayoutguide

**Comment by s4cha** [comment]
Yes yours is better! I didn't know how to make it loop :) I'm gonna update the PR

**Comment by s4cha** [comment]
@maxkonovalov should be good now :)

**Comment by maxkonovalov** [comment]
Cool!
I use https://ezgif.com for gifs

**Pull request merged**
