### PR TITLE
Add SPM intergration

### PR DESCRIPTION
**Pull request by dstranz**
* Add Swift Package Manager integration to use KeyboardLayoutGuide as dependency in Xcode 11

### CODE REVIEW

**Comment by s4cha** [comment]
@dstranz This is very cool! Thank you so much for taking the time to support SPM 🙏 🥇

**Comment by dstranz** [comment]
@s4cha Thank for the merge. It's needed to add new version tag to give proper SPM resolution. 

Now it could be used only with master branch, without version constraint.

**Comment by s4cha** [comment]
@dstranz I just released `1.4.2`, let me know if that works as expected :)

**Comment by dstranz** [comment]
@s4cha Now it's fine. Thanks.

**Pull request merged**
